// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro/why', 'intro/install', 'intro/speed', 'intro/versioning'],
    },
    {
      type: 'category',
      label: 'SSH2',
      items: ['ssh2/connect', 'ssh2/auth', 'ssh2/commands', 'ssh2/sftp', 'ssh2/diagnosis'],
    },
    {
      type: 'category',
      label: 'Public Keys',
      items: ['publickeys/overview', 'publickeys/rsa', 'publickeys/dsa', 'publickeys/ec', 'publickeys/dh', 'publickeys/jwt'],
    },
    {
      type: 'category',
      label: 'Symmetric Keys',
      items: ['symmetric/overview'],
    },
    {
      type: 'category',
      label: 'File Formats',
      items: ['asn1/x509', 'asn1/csr', 'asn1/spkac', 'asn1/crl'],
    },
    {
      type: 'category',
      label: 'Interoperability',
      items: [
        'interop/overview',
        'interop/python',
        'interop/java',
        'interop/javascript',
        'interop/nodejs',
        'interop/go',
        'interop/ruby',
        'interop/csharp',
        'interop/c',
        'interop/php',
      ],
    },
  ],
};

export default sidebars;
